# Generated by Django 5.2.5 on 2025-08-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
